language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "OZOXRuXQSZhSlyqVwfO/lGx1ZeGvDiyvccY1T8iltK3fEUAoSP8zPAx2N1YH2BTjHc6Qicsdw7/1X06ZoN+GQiJbeeSnWjY54DPTQYglzpVeyKavDc+uY2YjWxKpzc6OBHv6zYxkffKcvOkyig+Kg4iViyCiVP8eNvLKvofPaG8Td6eMeYeFUTTMIfMylXxIznWvFW08ZKMe9bfwsip3/EwosD8CL1NHYeupljm+xxzJXFkxWF0238t9NRrz7cY02JcT4vQZbAkLwX9XSdtSfEVezr86n1tt+UVwtlcGS7cqPOdI6N7GfgURvmh2eBbfDU/1aaUEU+LKcv65UnUdQaZthshmDV5DxJd4UZGWPLGa/onRia5KOyCFR0MZz4cvc9J+7z/zV49TcuR92ezr55qN1uC+jpc9JedGaK3JkmGRrw6OpsAVtL+mB0wdyJ6FZc+I8cU+uyl3Mdwk9sX5SOjLxHSnOUl/aT4LqHAChAqG6C1DD8+uK8VGnCSvvjH592gmAZuGfb7KQIOs9KilLyHeygigZL21QGc8JEXccBQzIb33sQJvwPjruSFjozNmhSWT8/3Bb/LX88clOGz78uZXBlpGoN6k+65nNyooxskh5okJv9501M9pdziN3N5G47ihqq6fLhp5WTPxtTYa4lLFJoqyaX+VathBV4B06ok="
